name: Update flake and Build Cache

on:
  schedule:
    - cron: '0 12 * * 1'
  workflow_dispatch:

jobs:
  update-and-build:
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
      - name: Fix AppArmor
        run: |
          sudo sysctl kernel.apparmor_restrict_unprivileged_userns=0
          sudo sysctl kernel.apparmor_restrict_unprivileged_unconfined=0
          sudo sysctl kernel.unprivileged_userns_clone=1

      - name: Maximize build space
        uses: wimpysworld/nothing-but-nix@main
        with:
          hatchet-protocol: 'cleave'

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/refs/heads/nixpkgs-unstable.tar.gz
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            substituters = https://cache.nixos.org/ https://firefly-cache.cachix.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= firefly-cache.cachix.org-1:R4ZfvGxjVaTVKQQ6kkl3klYwKvHzkU+COTr4v+3wIAE=
            system-features = gccarch-x86-64-v3 big-parallel

      - name: Setup cachix
        uses: cachix/cachix-action@v17
        with:
          name: firefly-cache
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Update flake.lock
        run: nix flake update

      - name: Commit and push if changed
        run: |
          git add flake.lock
          if ! git diff --staged --quiet; then
            git commit -m "chore: update flake.lock [automated]"
            git push
          fi

      - name: Build nix packages
        run: |
          timeout 5h nix run nixpkgs#nix-fast-build -- \
            --no-nom \
            -f .#packages.x86_64-linux
